name: Check

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: '.node-version'

      - name: Cache pnpm store
        uses: actions/cache@v4.2.0
        with:
          path: ~/.local/share/pnpm/store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: |
          corepack enable
          corepack pnpm install --frozen-lockfile

      - name: Cache video for testing
        id: cache-avsynctest-vga-1m
        uses: actions/cache@v4.2.0
        with:
          path: videos/avsynctest-vga-1m.mp4
          key: avsynctest-vga-1m

      - name: Run make check
        run: make check

  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: '.node-version'

      - name: Cache pnpm store
        uses: actions/cache@v4.2.0
        with:
          path: ~/.local/share/pnpm/store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: |
          corepack enable
          corepack pnpm install --frozen-lockfile

      - name: Cache video for testing
        id: cache-avsynctest-vga-1m
        uses: actions/cache@v4.2.0
        with:
          path: videos/avsynctest-vga-1m.mp4
          key: avsynctest-vga-1m

      - name: Run e2e
        run: xvfb-run -a make e2e

      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            playwright-report/
            test-results/
